sudo: required
services:
  - docker

before_install:
  - cd react-client
  - docker build -t baktoobasik/docker-practice-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baktoobasik/docker-practice-react npm run test

